version: '3'
services:
  webmail:
    build: .
    volumes:
      - .:/webmail
    ports:
      - 3000:3000
    container_name: webmail
    links:
      - db
    command: sh /webmail/scripts/startup.sh
    env_file: .env
    stdin_open: true
    tty: true
  db:
    image: postgres
    container_name: db
    env_file: .env